#Локальный конфиг

#Хост и порт приложения

ServiceHost = "0.0.0.0"
ServicePort = 80

[BMSTUNewsConfig]
SiteAddress = "api.www.bmstu.ru"
Protocol = "https"
CronTimeout = "15s"
DayLimit = 30

[FirstParse]
WorkerCount = 10
StepParseSlug = 200

